app:
  title: "Movie Python"
  icon: "fa5s.film" # Fallback qtawesome icon
  icon_path: "moviepython/resources/moviepython.png" # Preferred: Path to custom icon file
  window:
    width: 1000
    height: 700
    min_width: 700
    min_height: 500

logging:
  level: "DEBUG" # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: True # Log messages to [app_title].log
  log_to_console: True # Print log messages to the terminal/console
  clear_on_startup: True # Clear the log file each time the app starts

sidebar:
  title: "Movie Python"
  icon: "fa5s.film"
  sections:
    - title: "Main"
      items:
        - id: "home"
          title: "Home"
          icon: "fa5s.home"
          page: "HomePage" # Corresponds to HomePage class
        - id: "search"
          title: "Search"
          icon: "fa5s.search"
          page: "SearchPage" # Corresponds to SearchPage class
        - id: "pixnova"
          title: "Pixnova"
          icon: "fa5s.magic" # Example icon
          page: "PixnovaPage" # Corresponds to PixnovaPage class
    - title: "AI" # New AI section
      items:
        - id: "face_dashboard"
          title: "Face Dashboard"
          icon: "fa5s.user-circle" # Changed from fa5r to fa5s
          page: "FaceDashboardPage"
        - id: "face_review"
          title: "Face Review"
          icon: "fa5s.images" # Example icon
          page: "FaceReviewPage"
        - id: "face_reports" # New entry for Face Reports
          title: "Face Reports"
          icon: "fa5s.chart-bar" # Example icon
          page: "FaceReportsPage" # Links to the new page class
    - title: "Settings" # Moved Settings section to the end
      items:
        - id: "preferences"
          title: "Preferences"
          icon: "fa5s.cog"
          page: "PreferencesPage" # Corresponds to PreferencesPage class

# AI section removed for simplicity in this initial setup
# ai:
#  ...
